const fs = require('fs');
const csv = require('csv-parser');

function cleanString(str) {
    if (!str || typeof str !== 'string') {
        return '';
    }
    return str.replace(/\0/g, '').trim();
}

function getMimeType(filename) {
    const MAP = {
        123: 'application/vnd.lotus-1-2-3',
        '7z': 'application/x-compressed',
        pdf: 'application/pdf',
        mxu: 'video/vnd.mpegurl',
        nb: 'application/mathematica',
        nc: 'application/x-netcdf',
        ncx: 'application/x-dtbncx+xml',
        nef: 'image/x-nikon-nef',
        'n-gage': 'application/vnd.nokia.n-gage.symbian.install',
        ngdat: 'application/vnd.nokia.n-gage.data',
        nlu: 'application/vnd.neurolanguage.nlu',
        nml: 'application/vnd.enliven',
        nnd: 'application/vnd.noblenet-directory',
        nns: 'application/vnd.noblenet-sealer',
        nnw: 'application/vnd.noblenet-web',
        npx: 'image/vnd.net-fpx',
        nsf: 'application/vnd.lotus-notes',
        nws: 'message/rfc822',
        o: 'application/octet-stream',
        oa2: 'application/vnd.fujitsu.oasys2',
        oa3: 'application/vnd.fujitsu.oasys3',
        oas: 'application/vnd.fujitsu.oasys',
        obd: 'application/x-msbinder',
        obj: 'application/octet-stream',
        oda: 'application/oda',
        odb: 'application/vnd.oasis.opendocument.database',
        odc: 'application/vnd.oasis.opendocument.chart',
        odf: 'application/vnd.oasis.opendocument.formula',
        odft: 'application/vnd.oasis.opendocument.formula-template',
        odg: 'application/vnd.oasis.opendocument.graphics',
        odi: 'application/vnd.oasis.opendocument.image',
        odp: 'application/vnd.oasis.opendocument.presentation',
        ods: 'application/vnd.oasis.opendocument.spreadsheet',
        odt: 'application/vnd.oasis.opendocument.text',
        oga: 'audio/ogg',
        ogg: 'audio/ogg',
        ogv: 'video/ogg',
        ogx: 'application/ogg',
        onepkg: 'application/onenote',
        onetmp: 'application/onenote',
        onetoc: 'application/onenote',
        onetoc2: 'application/onenote',
        opf: 'application/oebps-package+xml',
        oprc: 'application/vnd.palm',
        opus: 'audio/opus',
        orf: 'image/x-olympus-orf',
        org: 'application/vnd.lotus-organizer',
        osf: 'application/vnd.yamaha.openscoreformat',
        osfpvg: 'application/vnd.yamaha.openscoreformat.osfpvg+xml',
        otc: 'application/vnd.oasis.opendocument.chart-template',
        otf: 'font/otf',
        otg: 'application/vnd.oasis.opendocument.graphics-template',
        oth: 'application/vnd.oasis.opendocument.text-web',
        oti: 'application/vnd.oasis.opendocument.image-template',
        otm: 'application/vnd.oasis.opendocument.text-master',
        otp: 'application/vnd.oasis.opendocument.presentation-template',
        ots: 'application/vnd.oasis.opendocument.spreadsheet-template',
        ott: 'application/vnd.oasis.opendocument.text-template',
        oxt: 'application/vnd.openofficeorg.extension',
        p: 'text/x-pascal',
        p10: 'application/pkcs10',
        p12: 'application/x-pkcs12',
        p7b: 'application/x-pkcs7-certificates',
        p7c: 'application/pkcs7-mime',
        p7m: 'application/pkcs7-mime',
        p7r: 'application/x-pkcs7-certreqresp',
        p7s: 'application/pkcs7-signature',
        pas: 'text/x-pascal',
        pbd: 'application/vnd.powerbuilder6',
        pbm: 'image/x-portable-bitmap',
        pcf: 'application/x-font-pcf',
        pcl: 'application/vnd.hp-pcl',
        pclxl: 'application/vnd.hp-pclxl',
        pct: 'image/x-pict',
        pcurl: 'application/vnd.curl.pcurl',
        pcx: 'image/x-pcx',
        pdb: 'application/vnd.palm',
        pdf: 'application/pdf',
        pef: 'image/x-pentax-pef',
        pfa: 'application/x-font-type1',
        pfb: 'application/x-font-type1',
        pfm: 'application/x-font-type1',
        pfr: 'application/font-tdpfr',
        pfx: 'application/x-pkcs12',
        pgm: 'image/x-portable-graymap',
        pgn: 'application/x-chess-pgn',
        pgp: 'application/pgp-encrypted',
        pic: 'image/x-pict',
        pjpg: 'image/pjpeg',
        pkg: 'application/octet-stream',
        pki: 'application/pkixcmp',
        pkipath: 'application/pkix-pkipath',
        pl: 'application/x-perl',
        plb: 'application/vnd.3gpp.pic-bw-large',
        plc: 'application/vnd.mobius.plc',
        plf: 'application/vnd.pocketlearn',
        pls: 'application/pls+xml',
        pm: 'application/x-perl',
        pml: 'application/vnd.ctc-posml',
        png: 'image/png',
        pnm: 'image/x-portable-anymap',
        portpkg: 'application/vnd.macports.portpkg',
        pot: 'application/vnd.ms-powerpoint',
        potm: 'application/vnd.ms-powerpoint.template.macroenabled.12',
        potx: 'application/vnd.openxmlformats-officedocument.presentationml.template',
        pp: 'text/x-pascal',
        ppa: 'application/vnd.ms-powerpoint',
        ppam: 'application/vnd.ms-powerpoint.addin.macroenabled.12',
        ppd: 'application/vnd.cups-ppd',
        ppm: 'image/x-portable-pixmap',
        pps: 'application/vnd.ms-powerpoint',
        ppsm: 'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
        ppsx: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
        ppt: 'application/vnd.ms-powerpoint',
        pptm: 'application/vnd.ms-powerpoint.presentation.macroenabled.12',
        pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        pqa: 'application/vnd.palm',
        prc: 'application/x-mobipocket-ebook',
        pre: 'application/vnd.lotus-freelance',
        prf: 'application/pics-rules',
        prql: 'application/prql',
        ps: 'application/postscript',
        psb: 'application/vnd.3gpp.pic-bw-small',
        psd: 'image/vnd.adobe.photoshop',
        psf: 'application/x-font-linux-psf',
        ptid: 'application/vnd.pvi.ptid1',
        ptx: 'image/x-pentax-pef',
        pub: 'application/x-mspublisher',
        pvb: 'application/vnd.3gpp.pic-bw-var',
        pwn: 'application/vnd.3m.post-it-notes',
        pwz: 'application/vnd.ms-powerpoint',
        py: 'text/x-python',
        pya: 'audio/vnd.ms-playready.media.pya',
        pyc: 'text/x-python',
        pyd: 'text/x-python',
        pyo: 'text/x-python',
        pyv: 'video/vnd.ms-playready.media.pyv',
        qam: 'application/vnd.epson.quickanime',
        qbo: 'application/vnd.intu.qbo',
        qfx: 'application/vnd.intu.qfx',
        qps: 'application/vnd.publishare-delta-tree',
        qt: 'video/quicktime',
        qwd: 'application/vnd.quark.quarkxpress',
        qwt: 'application/vnd.quark.quarkxpress',
        qxb: 'application/vnd.quark.quarkxpress',
        qxd: 'application/vnd.quark.quarkxpress',
        qxl: 'application/vnd.quark.quarkxpress',
        qxt: 'application/vnd.quark.quarkxpress',
        ra: 'audio/x-pn-realaudio',
        raf: 'image/x-fuji-raf',
        ram: 'audio/x-pn-realaudio',
        rar: 'application/vnd.rar',
        ras: 'image/x-cmu-raster',
        raw: 'image/x-panasonic-raw',
        rcprofile: 'application/vnd.ipunplugged.rcprofile',
        rdf: 'application/rdf+xml',
        rdz: 'application/vnd.data-vision.rdz',
        rep: 'application/vnd.businessobjects',
        res: 'application/x-dtbresource+xml',
        rgb: 'image/x-rgb',
        rif: 'application/reginfo+xml',
        rl: 'application/resource-lists+xml',
        rlc: 'image/vnd.fujixerox.edmics-rlc',
        rld: 'application/resource-lists-diff+xml',
        rm: 'application/vnd.rn-realmedia',
        rmi: 'audio/midi',
        rmp: 'audio/x-pn-realaudio-plugin',
        rms: 'application/vnd.jcp.javame.midlet-rms',
        rnc: 'application/relax-ng-compact-syntax',
        roff: 'text/troff',
        rpa: 'application/x-redhat-package-manager',
        rpm: 'application/x-rpm',
        rpss: 'application/vnd.nokia.radio-presets',
        rpst: 'application/vnd.nokia.radio-preset',
        rq: 'application/sparql-query',
        rs: 'application/rls-services+xml',
        rsd: 'application/rsd+xml',
        rss: 'application/rss+xml',
        rtf: 'application/rtf',
        rtx: 'text/richtext',
        rw2: 'image/x-panasonic-raw',
        rwl: 'image/x-panasonic-raw',
        s: 'text/x-asm',
        saf: 'application/vnd.yamaha.smaf-audio',
        sbml: 'application/sbml+xml',
        sc: 'application/vnd.ibm.secure-container',
        scd: 'application/x-msschedule',
        scm: 'application/vnd.lotus-screencam',
        scq: 'application/scvp-cv-request',
        scs: 'application/scvp-cv-response',
        scurl: 'text/vnd.curl.scurl',
        sda: 'application/vnd.stardivision.draw',
        sdc: 'application/vnd.stardivision.calc',
        sdd: 'application/vnd.stardivision.impress',
        sdkd: 'application/vnd.solent.sdkm+xml',
        sdkm: 'application/vnd.solent.sdkm+xml',
        sdp: 'application/sdp',
        sdw: 'application/vnd.stardivision.writer',
        see: 'application/vnd.seemail',
        seed: 'application/vnd.fdsn.seed',
        sema: 'application/vnd.sema',
        semd: 'application/vnd.semd',
        semf: 'application/vnd.semf',
        ser: 'application/java-serialized-object',
        setpay: 'application/set-payment-initiation',
        setreg: 'application/set-registration-initiation',
        'sfd-hdstx': 'application/vnd.hydrostatix.sof-data',
        sfs: 'application/vnd.spotfire.sfs',
        sgl: 'application/vnd.stardivision.writer-global',
        sgm: 'text/sgml',
        sgml: 'text/sgml',
        sh: 'application/x-sh',
        shar: 'application/x-shar',
        shf: 'application/shf+xml',
        si: 'text/vnd.wap.si',
        sic: 'application/vnd.wap.sic',
        sig: 'application/pgp-signature',
        silo: 'model/mesh',
        sis: 'application/vnd.symbian.install',
        sisx: 'application/vnd.symbian.install',
        sit: 'application/x-stuffit',
        sitx: 'application/x-stuffitx',
        skd: 'application/vnd.koan',
        skm: 'application/vnd.koan',
        skp: 'application/vnd.koan',
        skt: 'application/vnd.koan',
        sl: 'text/vnd.wap.sl',
        slc: 'application/vnd.wap.slc',
        sldm: 'application/vnd.ms-powerpoint.slide.macroenabled.12',
        sldx: 'application/vnd.openxmlformats-officedocument.presentationml.slide',
        slt: 'application/vnd.epson.salt',
        smf: 'application/vnd.stardivision.math',
        smi: 'application/smil+xml',
        smil: 'application/smil+xml',
        snd: 'audio/basic',
        snf: 'application/x-font-snf',
        so: 'application/octet-stream',
        spc: 'application/x-pkcs7-certificates',
        spf: 'application/vnd.yamaha.smaf-phrase',
        spl: 'application/x-futuresplash',
        spot: 'text/vnd.in3d.spot',
        spp: 'application/scvp-vp-response',
        spq: 'application/scvp-vp-request',
        spx: 'audio/ogg',
        sqlite: 'application/vnd.sqlite3',
        sqlite3: 'application/vnd.sqlite3',
        'sqlite-shm': 'application/vnd.sqlite3',
        'sqlite-wal': 'application/vnd.sqlite3',
        sr2: 'image/x-sony-sr2',
        src: 'application/x-wais-source',
        srf: 'image/x-sony-srf',
        srx: 'application/sparql-results+xml',
        sse: 'application/vnd.kodak-descriptor',
        ssf: 'application/vnd.epson.ssf',
        ssml: 'application/ssml+xml',
        stc: 'application/vnd.sun.xml.calc.template',
        std: 'application/vnd.sun.xml.draw.template',
        stf: 'application/vnd.wt.stf',
        sti: 'application/vnd.sun.xml.impress.template',
        stk: 'application/hyperstudio',
        stl: 'application/vnd.ms-pki.stl',
        str: 'application/vnd.pg.format',
        stw: 'application/vnd.sun.xml.writer.template',
        sus: 'application/vnd.sus-calendar',
        susp: 'application/vnd.sus-calendar',
        sv4cpio: 'application/x-sv4cpio',
        sv4crc: 'application/x-sv4crc',
        svd: 'application/vnd.svd',
        svg: 'image/svg+xml',
        svgz: 'image/svg+xml',
        swa: 'application/x-director',
        swf: 'application/x-shockwave-flash',
        swi: 'application/vnd.arastra.swi',
        sxc: 'application/vnd.sun.xml.calc',
        sxd: 'application/vnd.sun.xml.draw',
        sxg: 'application/vnd.sun.xml.writer.global',
        sxi: 'application/vnd.sun.xml.impress',
        sxm: 'application/vnd.sun.xml.math',
        sxw: 'application/vnd.sun.xml.writer',
        t: 'text/troff',
        tao: 'application/vnd.tao.intent-module-archive',
        tar: 'application/x-tar',
        tcap: 'application/vnd.3gpp2.tcap',
        tcl: 'application/x-tcl',
        teacher: 'application/vnd.smart.teacher',
        test: 'test/mimetype',
        tex: 'application/x-tex',
        texi: 'application/x-texinfo',
        texinfo: 'application/x-texinfo',
        text: 'text/plain',
        tfm: 'application/x-tex-tfm',
        tgz: 'application/gzip',
        tif: 'image/tiff',
        tiff: 'image/tiff',
        tmo: 'application/vnd.tmobile-livetv',
        torrent: 'application/x-bittorrent',
        tpl: 'application/vnd.groove-tool-template',
        tpt: 'application/vnd.trid.tpt',
        tr: 'text/troff',
        tra: 'application/vnd.trueapp',
        trm: 'application/x-msterminal',
        ts: 'video/mp2t',
        tsv: 'text/tab-separated-values',
        ttc: 'application/x-font-ttf',
        ttf: 'application/x-font-ttf',
        twd: 'application/vnd.simtech-mindmapper',
        twds: 'application/vnd.simtech-mindmapper',
        txd: 'application/vnd.genomatix.tuxedo',
        txf: 'application/vnd.mobius.txf',
        txt: 'text/plain',
        u32: 'application/x-authorware-bin',
        udeb: 'application/vnd.debian.binary-package',
        ufd: 'application/vnd.ufdl',
        ufdl: 'application/vnd.ufdl',
        umj: 'application/vnd.umajin',
        unityweb: 'application/vnd.unity',
        uoml: 'application/vnd.uoml+xml',
        uri: 'text/uri-list',
        uris: 'text/uri-list',
        urls: 'text/uri-list',
        ustar: 'application/x-ustar',
        utz: 'application/vnd.uiq.theme',
        uu: 'text/x-uuencode',
        vcd: 'application/x-cdlink',
        vcf: 'text/x-vcard',
        vcg: 'application/vnd.groove-vcard',
        vcs: 'text/x-vcalendar',
        vcx: 'application/vnd.vcx',
        vis: 'application/vnd.visionary',
        viv: 'video/vnd.vivo',
        vor: 'application/vnd.stardivision.writer',
        vox: 'application/x-authorware-bin',
        vrml: 'model/vrml',
        vsd: 'application/vnd.visio',
        vsdx: 'application/vnd.visio',
        vsf: 'application/vnd.vsf',
        vss: 'application/vnd.visio',
        vssm: 'application/vnd.visio',
        vssx: 'application/vnd.visio',
        vst: 'application/vnd.visio',
        vstm: 'application/vnd.visio',
        vstx: 'application/vnd.visio',
        vsw: 'application/vnd.visio',
        vtu: 'model/vnd.vtu',
        vxml: 'application/voicexml+xml',
        w3d: 'application/x-director',
        wad: 'application/x-doom',
        wasm: 'application/wasm',
        wav: 'audio/vnd.wav',
        wax: 'audio/x-ms-wax',
        wbmp: 'image/vnd.wap.wbmp',
        wbs: 'application/vnd.criticaltools.wbs+xml',
        wbxml: 'application/vnd.wap.wbxml',
        wcm: 'application/vnd.ms-works',
        wdb: 'application/vnd.ms-works',
        weba: 'audio/webm',
        webm: 'video/webm',
        webp: 'image/webp',
        whl: 'text/x-python',
        wiz: 'application/msword',
        wks: 'application/vnd.ms-works',
        wm: 'video/x-ms-wm',
        wma: 'audio/x-ms-wma',
        wmd: 'application/x-ms-wmd',
        wmf: 'application/x-msmetafile',
        wml: 'text/vnd.wap.wml',
        wmlc: 'application/vnd.wap.wmlc',
        wmls: 'text/vnd.wap.wmlscript',
        wmlsc: 'application/vnd.wap.wmlscriptc',
        wmv: 'video/x-ms-wmv',
        wmx: 'video/x-ms-wmx',
        wmz: 'application/x-ms-wmz',
        woff: 'font/woff',
        woff2: 'font/woff2',
        wpd: 'application/vnd.wordperfect',
        wpl: 'application/vnd.ms-wpl',
        wps: 'application/vnd.ms-works',
        wqd: 'application/vnd.wqd',
        wri: 'application/x-mswrite',
        wrl: 'model/vrml',
        wsdl: 'application/wsdl+xml',
        wspolicy: 'application/wspolicy+xml',
        wtb: 'application/vnd.webturbo',
        wvx: 'video/x-ms-wvx',
        x32: 'application/x-authorware-bin',
        x3d: 'application/vnd.hzn-3d-crossword',
        x3f: 'image/x-sigma-x3f',
        xap: 'application/x-silverlight-app',
        xar: 'application/vnd.xara',
        xbap: 'application/x-ms-xbap',
        xbd: 'application/vnd.fujixerox.docuworks.binder',
        xbm: 'image/x-xbitmap',
        xdm: 'application/vnd.syncml.dm+xml',
        xdp: 'application/vnd.adobe.xdp+xml',
        xdw: 'application/vnd.fujixerox.docuworks',
        xenc: 'application/xenc+xml',
        xer: 'application/patch-ops-error+xml',
        xfdf: 'application/vnd.adobe.xfdf',
        xfdl: 'application/vnd.xfdl',
        xht: 'application/xhtml+xml',
        xhtml: 'application/xhtml+xml',
        xhvml: 'application/xv+xml',
        xif: 'image/vnd.xiff',
        xla: 'application/vnd.ms-excel',
        xlam: 'application/vnd.ms-excel.addin.macroenabled.12',
        xlb: 'application/vnd.ms-excel',
        xlc: 'application/vnd.ms-excel',
        xlm: 'application/vnd.ms-excel',
        xls: 'application/vnd.ms-excel',
        xlsb: 'application/vnd.ms-excel.sheet.binary.macroenabled.12',
        xlsm: 'application/vnd.ms-excel.sheet.macroenabled.12',
        xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        xlt: 'application/vnd.ms-excel',
        xltm: 'application/vnd.ms-excel.template.macroenabled.12',
        xltx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        xlw: 'application/vnd.ms-excel',
        xml: 'application/xml',
        xo: 'application/vnd.olpc-sugar',
        xop: 'application/xop+xml',
        xpdl: 'application/xml',
        xpi: 'application/x-xpinstall',
        xpm: 'image/x-xpixmap',
        xpr: 'application/vnd.is-xpr',
        xps: 'application/vnd.ms-xpsdocument',
        xpw: 'application/vnd.intercon.formnet',
        xpx: 'application/vnd.intercon.formnet',
        xsl: 'application/xml',
        xslt: 'application/xslt+xml',
        xsm: 'application/vnd.syncml+xml',
        xspf: 'application/xspf+xml',
        xul: 'application/vnd.mozilla.xul+xml',
        xvm: 'application/xv+xml',
        xvml: 'application/xv+xml',
        xwd: 'image/x-xwindowdump',
        xyz: 'chemical/x-xyz',
        yaml: 'application/yaml',
        yml: 'application/yaml',
        zabw: 'application/x-abiword',
        zaz: 'application/vnd.zzazz.deck+xml',
        zip: 'application/zip',
        zir: 'application/vnd.zul',
        zirz: 'application/vnd.zul',
        zmm: 'application/vnd.handheld-entertainment+xml',
    };

    const cleanFilename = cleanString(filename);

    if (!cleanFilename) {
        return 'application/octet-stream';
    }

    const regexpResult = /^.*\.(.+)$/.exec(cleanFilename);
    if (regexpResult) {
        const extension = regexpResult[1].toLowerCase();
        const mappedType = MAP[extension];
        if (mappedType) return mappedType;
    }

    return 'application/octet-stream';
}

function csvToJson(csvFilePath, jsonFilePath) {
    return new Promise((resolve, reject) => {
        const results = [];

        fs.createReadStream(csvFilePath, { encoding: 'utf16le' })
            .pipe(
                csv({
                    separator: ',',
                    headers: ['id', 'name', 'base'],
                    skipEmptyLines: true,
                    trim: true,
                })
            )
            .on('data', (data) => {
                const cleanData = {
                    id: cleanString(data.id),
                    name: cleanString(data.name),
                    base: cleanString(data.base),
                };

                const mimeType = getMimeType(cleanData.name);

                results.push({
                    obj: cleanData.id,
                    filename: cleanData.name,
                    base64: cleanData.base,
                    mimeType: mimeType,
                });
            })
            .on('end', () => {
                try {
                    fs.writeFileSync(jsonFilePath, JSON.stringify(results, null, 2), 'utf8');
                    console.log(`Конвертация завершена. Обработано ${results.length} записей.`);
                    resolve(results);
                } catch (error) {
                    reject(error);
                }
            })
            .on('error', (error) => {
                reject(error);
            });
    });
}

csvToJson('07-Recommendations_opened_fin.csv', '07-Recommendations_opened_fin.json')
    .then((results) => {
        console.log('Успешно сконвертировано записей:', results.length);
    })
    .catch((error) => {
        console.error('Ошибка при конвертации:', error);
    });
